// Package firewall emits an nftables ruleset for transparent-proxy TPROXY
// + fwmark + ip-rule/route plumbing. The renderer is OS-independent
// (produces nft script text); apply uses `nft -f -` and is Linux-only.
//
// Design notes:
//   - One table `inet vctl` owns everything; this avoids collisions with
//     any other tables on the router.
//   - Sets are named consistently so dnsmasq nftset hooks can populate them
//     (vctl_direct4 / vctl_direct6 / vctl_proxy4 / vctl_proxy6 / vctl_block).
//   - Reserved ports (DHCP, etc.) and local destinations bypass TPROXY.
//   - A "policy: accept" fallback means any rule typo doesn't black-hole the
//     router — operator must explicitly choose to drop.
package firewall

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// Spec is everything the renderer needs to emit a ruleset.
type Spec struct {
	TproxyPort  int    // Xray tproxy listen port
	FwMark      int    // mark applied to tproxied packets
	TableName   string // default "vctl"
	RtTable     int    // routing table id for fwmark route (default 100)
	IPv6Enabled bool

	// Static bypass nets — typical LAN-side ranges that must NEVER be proxied.
	BypassV4 []string
	BypassV6 []string

	// Source bypass: don't proxy traffic FROM these addresses. Default: empty.
	SourceBypassV4 []string
	SourceBypassV6 []string

	// Hook into existing fakedns / split DNS: nftsets dnsmasq populates.
	DirectSetV4 string // dnsmasq's nftset name for "direct" domains, ipv4
	DirectSetV6 string
	ProxySetV4  string
	ProxySetV6  string
}

// DefaultSpec returns a sensible baseline matching the project's fleet contour.
func DefaultSpec(tproxyPort, fwmark int) Spec {
	return Spec{
		TproxyPort:  tproxyPort,
		FwMark:      fwmark,
		TableName:   "vctl",
		RtTable:     100,
		IPv6Enabled: true,
		BypassV4: []string{
			"0.0.0.0/8", "10.0.0.0/8", "100.64.0.0/10", "127.0.0.0/8",
			"169.254.0.0/16", "172.16.0.0/12", "192.0.0.0/24", "192.0.2.0/24",
			"192.88.99.0/24", "192.168.0.0/16", "198.18.0.0/15", "198.51.100.0/24",
			"203.0.113.0/24", "224.0.0.0/3",
		},
		BypassV6: []string{
			"::1/128", "fc00::/7", "fe80::/10", "ff00::/8",
		},
		DirectSetV4: "vctl_direct4",
		DirectSetV6: "vctl_direct6",
		ProxySetV4:  "vctl_proxy4",
		ProxySetV6:  "vctl_proxy6",
	}
}

// Block form: the whole table is declared in a single transaction. nft -f -
// runs everything as one netlink batch — atomic replace, no race window where
// rules are missing.
const tmplText = `# Generated by vctl — do not edit by hand.
# table: {{ .TableName }} (inet)
# tproxy port: {{ .TproxyPort }}, fwmark: 0x{{ printf "%x" .FwMark }}

table inet {{ .TableName }} {
  set {{ .DirectSetV4 }} { type ipv4_addr; flags interval; auto-merge; }
  set {{ .ProxySetV4 }}  { type ipv4_addr; flags interval; auto-merge; }
{{- if .IPv6Enabled }}
  set {{ .DirectSetV6 }} { type ipv6_addr; flags interval; auto-merge; }
  set {{ .ProxySetV6 }}  { type ipv6_addr; flags interval; auto-merge; }
{{- end }}

  set bypass4 { type ipv4_addr; flags interval; auto-merge;
    elements = { {{ join .BypassV4 ", " }} }; }
{{- if .IPv6Enabled }}
  set bypass6 { type ipv6_addr; flags interval; auto-merge;
    elements = { {{ join .BypassV6 ", " }} }; }
{{- end }}

  chain prerouting {
    type filter hook prerouting priority mangle; policy accept;
    fib daddr type { local, broadcast, multicast } return
    ip  daddr @bypass4 return
{{- if .IPv6Enabled }}
    ip6 daddr @bypass6 return
{{- end }}
    ip  daddr @{{ .DirectSetV4 }} return
{{- if .IPv6Enabled }}
    ip6 daddr @{{ .DirectSetV6 }} return
{{- end }}
    meta l4proto { tcp, udp } tproxy to :{{ .TproxyPort }} meta mark set 0x{{ printf "%x" .FwMark }} accept
  }

  chain output {
    type route hook output priority mangle; policy accept;
    meta mark 0x{{ printf "%x" .FwMark }} return
    fib daddr type { local, broadcast, multicast } return
    ip  daddr @bypass4 return
{{- if .IPv6Enabled }}
    ip6 daddr @bypass6 return
{{- end }}
    ip  daddr @{{ .DirectSetV4 }} return
{{- if .IPv6Enabled }}
    ip6 daddr @{{ .DirectSetV6 }} return
{{- end }}
    meta l4proto { tcp, udp } meta mark set 0x{{ printf "%x" .FwMark }}
  }
}

# Routing companion commands (run separately by 'vctl firewall routing'):
#   ip rule add fwmark 0x{{ printf "%x" .FwMark }} lookup {{ .RtTable }} pref 100
#   ip route add local 0.0.0.0/0 dev lo table {{ .RtTable }}
{{- if .IPv6Enabled }}
#   ip -6 rule add fwmark 0x{{ printf "%x" .FwMark }} lookup {{ .RtTable }} pref 100
#   ip -6 route add local ::/0 dev lo table {{ .RtTable }}
{{- end }}
`

// Render returns the nft script text for the given spec.
func Render(s Spec) (string, error) {
	if s.TableName == "" {
		s.TableName = "vctl"
	}
	if s.RtTable == 0 {
		s.RtTable = 100
	}
	t := template.Must(template.New("nft").Funcs(template.FuncMap{
		"join": strings.Join,
	}).Parse(tmplText))
	var buf bytes.Buffer
	if err := t.Execute(&buf, s); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// RoutingCommands returns the ip rule/route commands needed alongside nft.
func RoutingCommands(s Spec) []string {
	cmds := []string{
		fmt.Sprintf("ip rule add fwmark 0x%x lookup %d pref 100", s.FwMark, s.RtTable),
		fmt.Sprintf("ip route add local 0.0.0.0/0 dev lo table %d", s.RtTable),
	}
	if s.IPv6Enabled {
		cmds = append(cmds,
			fmt.Sprintf("ip -6 rule add fwmark 0x%x lookup %d pref 100", s.FwMark, s.RtTable),
			fmt.Sprintf("ip -6 route add local ::/0 dev lo table %d", s.RtTable),
		)
	}
	return cmds
}

// RevertCommands returns the commands to undo what we set up. Operator runs these
// (or our --apply tooling does) to clean up an applied ruleset on shutdown.
func RevertCommands(s Spec) []string {
	cmds := []string{
		"nft flush table inet " + s.TableName,
		"nft delete table inet " + s.TableName,
		fmt.Sprintf("ip rule del fwmark 0x%x lookup %d", s.FwMark, s.RtTable),
		fmt.Sprintf("ip route del local 0.0.0.0/0 dev lo table %d", s.RtTable),
	}
	if s.IPv6Enabled {
		cmds = append(cmds,
			fmt.Sprintf("ip -6 rule del fwmark 0x%x lookup %d", s.FwMark, s.RtTable),
			fmt.Sprintf("ip -6 route del local ::/0 dev lo table %d", s.RtTable),
		)
	}
	return cmds
}
