// Package dns generates dnsmasq config fragments to integrate with our
// nftables sets — populates split-routing nftsets per domain.
package dns

import (
	"bytes"
	"fmt"
	"strings"
)

// Fragment describes a dnsmasq drop-in fragment to write under
// /etc/dnsmasq.d/.
type Fragment struct {
	Filename string
	Content  string
}

// SplitConfig captures the operator's intent: per "category", populate which
// nftset (v4 and/or v6) when a matching domain is queried.
type SplitConfig struct {
	// LocalListen — make dnsmasq listen on this address:port (optional).
	LocalListen string
	// UpstreamServers — list of "host" or "host#port" entries.
	UpstreamServers []string
	// PerDomain — domain group -> nftset destinations. dnsmasq nftset syntax:
	//   nftset=/domain1/domain2/4#inet#vctl#vctl_direct4,6#inet#vctl#vctl_direct6
	PerDomain []DomainGroup
	// CacheSize for dnsmasq.
	CacheSize int
}

type DomainGroup struct {
	// Domains is the list of base domains (without leading dot).
	Domains []string
	// SetV4, SetV6 are the nft set names within the inet/vctl table.
	SetV4 string
	SetV6 string
	// Comment is a human-readable label embedded as a comment.
	Comment string
}

// Render returns a single dnsmasq.d fragment file.
func Render(c SplitConfig) Fragment {
	var b bytes.Buffer
	b.WriteString("# Generated by vctl — split DNS hooks into nftables sets\n")
	if c.LocalListen != "" {
		fmt.Fprintf(&b, "listen-address=%s\n", c.LocalListen)
	}
	for _, srv := range c.UpstreamServers {
		fmt.Fprintf(&b, "server=%s\n", srv)
	}
	if c.CacheSize > 0 {
		fmt.Fprintf(&b, "cache-size=%d\n", c.CacheSize)
	}
	for _, g := range c.PerDomain {
		if g.Comment != "" {
			fmt.Fprintf(&b, "# %s\n", g.Comment)
		}
		domains := strings.Join(g.Domains, "/")
		var parts []string
		if g.SetV4 != "" {
			parts = append(parts, fmt.Sprintf("4#inet#vctl#%s", g.SetV4))
		}
		if g.SetV6 != "" {
			parts = append(parts, fmt.Sprintf("6#inet#vctl#%s", g.SetV6))
		}
		if len(parts) > 0 {
			fmt.Fprintf(&b, "nftset=/%s/%s\n", domains, strings.Join(parts, ","))
		}
	}
	return Fragment{
		Filename: "vctl-split.conf",
		Content:  b.String(),
	}
}
