package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"vectra-controller-pro/internal/coreengine/xray"
	"vectra-controller-pro/internal/logging"
	"vectra-controller-pro/internal/memguard"
)

// PassWall-compatible routing, the daemon's side (the why is in
// internal/coreengine/xray/passwall.go). With UCI route_source 'passwall' the
// router routes by PassWall2's own configuration — the one the panel keeps on
// every fleet router — generated by PassWall2's own code and run by vctl.

const routeSourcePassWall = "passwall"

// passwallGenerator is PassWall2's xray config generator; passwallAssetDir
// where PassWall2 keeps the geo files its rules name.
var (
	passwallGenerator = "/usr/lib/lua/luci/passwall2/util_xray.lua"
	passwallUCIFile   = "/etc/config/passwall2"
)

const passwallDefaultAssetDir = "/usr/share/v2ray/"

// passwallMode: the router routes by the operator's PassWall-shaped route
// policy — generated by PassWall2 ('passwall') or by vctl ('native',
// native_source.go). Everything but the generator and where the policy and
// its geo files live is the same for both.
func (d *daemon) passwallMode() bool {
	return d.cfg.RouteSource == routeSourcePassWall || d.cfg.RouteSource == routeSourceNative
}

// documentPath is where the document the render is made from is kept: the
// provider's, or PassWall's adapted configuration — in a file of its own, so
// that turning route_source back finds the provider's document as it was.
func (d *daemon) documentPath() string {
	if d.passwallMode() {
		return passwallDocumentPath(d.cfg.ProviderConfigPath)
	}
	return d.cfg.ProviderConfigPath
}

func passwallDocumentPath(providerPath string) string {
	return filepath.Join(filepath.Dir(providerPath), "passwall-config.json")
}

// uciGet reads one UCI value ("" when unset). A seam: tests replace it.
var uciGet = func(key string) string {
	out, err := exec.Command("uci", "-q", "get", key).Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

// passwallAssetDir is where PassWall2 reads geosite/geoip from.
func passwallAssetDir() string {
	if v := uciGet("passwall2.@global_rules[0].v2ray_location_asset"); v != "" {
		return v
	}
	return passwallDefaultAssetDir
}

// passwallArgs is what PassWall2's own start (app.sh, run_global and
// run_xray) passes to gen_config for the global transparent proxy — read
// from the same UCI — with vctl's tproxy port and DNS port. directDNS is the
// WAN's resolver PassWall calls AUTO_DNS.
func passwallArgs(get func(string) string, tproxyPort, dnsPort int, directDNS string) (map[string]string, error) {
	g := func(opt, def string) string {
		if v := get("passwall2.@global[0]." + opt); v != "" {
			return v
		}
		return def
	}
	node := g("node", "")
	if node == "" {
		return nil, errors.New("passwall2 has no global node")
	}
	a := map[string]string{
		"loglevel":                  g("loglevel", "warning"),
		"flag":                      "global",
		"node":                      node,
		"redir_port":                strconv.Itoa(tproxyPort),
		"tcp_proxy_way":             "tproxy",
		"dns_listen_port":           strconv.Itoa(dnsPort),
		"direct_dns_query_strategy": g("direct_dns_query_strategy", "UseIP"),
		"remote_dns_query_strategy": g("remote_dns_query_strategy", "UseIPv4"),
	}
	if v := get("passwall2.@global[0].dns_cache"); v != "" {
		a["dns_cache"] = v
	}
	if directDNS != "" {
		a["direct_dns_udp_server"] = directDNS
		a["direct_dns_udp_port"] = "53"
	}
	proto := g("remote_dns_protocol", "")
	if proto != "" {
		a["remote_dns_protocol"] = proto
		if v := g("remote_dns_detour", ""); v != "" {
			a["remote_dns_detour"] = v
		}
		switch proto {
		case "udp", "quic", "tcp", "tls":
			host, port := splitDNS(g("remote_dns", "1.1.1.1"))
			kind := "udp"
			if proto == "tcp" || proto == "tls" {
				kind = "tcp"
			}
			a["remote_dns_"+kind+"_server"] = host
			a["remote_dns_"+kind+"_port"] = port
		case "doh", "http3":
			raw := g("remote_dns_doh", "https://1.1.1.1/dns-query")
			u, bootstrap, _ := strings.Cut(raw, ",")
			pu, err := url.Parse(u)
			if err != nil || pu.Hostname() == "" {
				return nil, fmt.Errorf("passwall2 remote_dns_doh %q is not a URL", u)
			}
			port := pu.Port()
			if port == "" {
				port = "443"
			}
			a["remote_dns_doh_url"] = u
			a["remote_dns_doh_host"] = pu.Hostname()
			a["remote_dns_doh_port"] = port
			if net.ParseIP(pu.Hostname()) != nil {
				bootstrap = pu.Hostname()
			}
			if bootstrap != "" {
				a["remote_dns_doh_ip"] = bootstrap
			}
		}
		if g("remote_fakedns", "0") == "1" {
			a["remote_dns_fake"] = "1"
			a["remote_dns_fake_strategy"] = a["remote_dns_query_strategy"]
		}
		if v := g("remote_dns_client_ip", ""); v != "" {
			a["remote_dns_client_ip"] = v
		}
	}
	return a, nil
}

func splitDNS(s string) (host, port string) {
	s = strings.TrimSpace(strings.SplitN(s, ",", 2)[0])
	s = strings.ReplaceAll(s, "#", ":")
	if h, p, err := net.SplitHostPort(s); err == nil {
		return h, p
	}
	return s, "53"
}

// wanResolver is the WAN's first IPv4 resolver (netifd's resolv.conf.auto),
// what PassWall's direct DNS asks; "" when there is none.
func wanResolver(root string) string {
	for _, f := range []string{"tmp/resolv.conf.d/resolv.conf.auto", "tmp/resolv.conf.auto"} {
		b, err := os.ReadFile(filepath.Join(root, f))
		if err != nil {
			continue
		}
		for _, line := range strings.Split(string(b), "\n") {
			fields := strings.Fields(line)
			if len(fields) >= 2 && fields[0] == "nameserver" && isIPv4(fields[1]) {
				return fields[1]
			}
		}
	}
	return ""
}

// generatePassWall runs PassWall2's generator and returns its xray JSON.
func (d *daemon) generatePassWall(ctx context.Context) ([]byte, error) {
	if d.desired == nil || d.desired.Inbounds.Tproxy == nil {
		return nil, errors.New("no operator config with a tproxy inbound")
	}
	if _, err := os.Stat(passwallGenerator); err != nil {
		return nil, fmt.Errorf("PassWall2's generator is not installed (%s)", passwallGenerator)
	}
	_, dnsPort, _ := net.SplitHostPort(xray.DefaultDNSListen)
	dp, _ := strconv.Atoi(dnsPort)
	resolver := wanResolver(d.etcRoot())
	if resolver == "" {
		resolver = xray.DefaultDirectResolvers[0]
	}
	args, err := passwallArgs(uciGet, d.desired.Inbounds.Tproxy.Port, dp, resolver)
	if err != nil {
		return nil, err
	}
	j, _ := json.Marshal(args)
	c, cancel := context.WithTimeout(ctx, 60*time.Second)
	defer cancel()
	cmd := exec.CommandContext(c, "lua", passwallGenerator, "gen_config", string(j))
	var out, stderr bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &stderr
	err = cmd.Start()
	if err == nil {
		// Beside the running xray, the generator is the one to lose if the
		// router runs out (the sync is retried; what runs keeps running).
		_ = memguard.SetOOMScoreAdj(cmd.Process.Pid, memguard.TransientAdj)
		err = cmd.Wait()
	}
	if err != nil {
		return nil, fmt.Errorf("PassWall2's generator failed: %w: %s", err, tail(strings.TrimSpace(stderr.String()), 300))
	}
	if !json.Valid(out.Bytes()) {
		return nil, fmt.Errorf("PassWall2's generator gave no JSON (%d bytes): %s", out.Len(), tail(strings.TrimSpace(stderr.String()), 300))
	}
	return out.Bytes(), nil
}

// syncPassWall renders from PassWall2's configuration: generate, adapt, and
// install it as the provider document — with every one of vctl's checks: the
// splice's, xray -test, the atomic write. Nothing is installed when anything
// fails; what runs keeps running. forceReload restarts xray even when the
// document is the same (its geo files changed).
func (d *daemon) syncPassWall(ctx context.Context, forceReload bool) error {
	generate, by := d.generatePassWall, "PassWall2's generator"
	if d.nativeMode() {
		generate, by = d.generateNative, "vctl's generator"
	}
	raw, err := generate(ctx)
	if err != nil {
		return err
	}
	// The first native render imported the policy's own geo files: xray's
	// next start reads those.
	if d.sup != nil {
		d.sup.SetAssetDir(d.routeAssetDir())
	}
	if d.collector != nil {
		d.collector.SetAssetDir(d.routeAssetDir())
	}
	tag := "tproxy-in"
	if d.desired.Inbounds.Tproxy.Tag != "" {
		tag = d.desired.Inbounds.Tproxy.Tag
	}
	doc, pres, err := xray.AdaptPassWall(raw, tag)
	if err != nil {
		return err
	}
	d.passwallSniffing = &pres.Sniffing
	d.rebuildApplier()
	res, err := d.applyProvider(ctx, doc, forceReload)
	if err != nil {
		return err
	}
	d.reloadAfterApply(ctx, res, doc)
	if forceReload && !res.Changed && d.supStarted {
		// The same document, new geo files: xray reads them at its start.
		if err := d.sup.Reload(d.supCtx); err != nil {
			logging.L().Warn("xray reload for PassWall2's new geo files failed", "err", err.Error())
		}
	}
	if res.Changed {
		logging.L().Info("routing by the operator's route policy", "generator", by, "rules", pres.Rules, "fakedns", strings.Join(pres.FakeDNSPools, ","), "digest", shortDigest(res.AppliedDigest))
	}
	if err := d.persist(); err != nil {
		logging.L().Warn("persist state after a PassWall sync", "err", err.Error())
	}
	return nil
}

// passwallStamp fingerprints what PassWall's configuration is made from:
// its UCI and the WAN's resolver (regenerate when they change), and its geo
// files (xray loads them at its start: restart when they change).
func (d *daemon) passwallStamp() (config, geo string) {
	st := func(p string) string {
		fi, err := os.Stat(p)
		if err != nil {
			return "-"
		}
		return fmt.Sprintf("%d/%d", fi.ModTime().UnixNano(), fi.Size())
	}
	policy := passwallUCIFile
	if d.nativeMode() {
		policy = nativeStorePath
	}
	config = st(policy) + "|" + wanResolver(d.etcRoot())
	dir := d.routeAssetDir()
	geo = st(filepath.Join(dir, "geosite.dat")) + "|" + st(filepath.Join(dir, "geoip.dat"))
	return config, geo
}

// passwallSyncBackoff is how long a failed sync waits before the next try:
// the next loop, unless the router was too short of memory to check the
// result — then running PassWall's generator again every minute only to be
// refused again is what it cannot afford.
func passwallSyncBackoff(err error) time.Duration {
	if errors.Is(err, xray.ErrLowMemory) {
		return directRetry
	}
	return 0
}

// maybeSyncPassWall re-renders when PassWall's configuration changed since
// the last sync (the panel's route policy, the nightly node update, a new
// WAN resolver) and restarts xray when its geo files did. A failure keeps
// what runs and is tried again at the next change... or the next minute.
func (d *daemon) maybeSyncPassWall(ctx context.Context) {
	if !d.passwallMode() || d.desired == nil || time.Now().Before(d.passwallRetryAt) {
		return
	}
	cfgStamp, geoStamp := d.passwallStamp()
	if cfgStamp == d.passwallCfgStamp && geoStamp == d.passwallGeoStamp {
		return
	}
	geoChanged := d.passwallGeoStamp != "" && geoStamp != d.passwallGeoStamp
	if err := d.syncPassWall(ctx, geoChanged); err != nil {
		d.passwallRetryAt = time.Now().Add(passwallSyncBackoff(err))
		logging.L().Warn("could not render from the operator's route policy; what runs keeps running", "routeSource", d.cfg.RouteSource, "err", err.Error())
		return
	}
	d.passwallCfgStamp, d.passwallGeoStamp = cfgStamp, geoStamp
}
